config/routes.rb
Phccodesnipper::Engine.routes.draw do

  # Script Snippet Routes
  namespace :script do
    resources :snippets, class_name: 'Phccodesnipper::Script::Snippet' do
      resources :urls, class_name: 'Phccodesnipper::Script::Url'
    end
  end

  # PHCAccounts Routes
  mount Phcaccounts::Engine, :at => '/'

end

app/models/phccodesnipper/application_record.rb
module Phccodesnipper
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/phccodesnipper/script.rb
module Phccodesnipper
  module Script
    def self.table_name_prefix
      'phccodesnipper_script_'
    end
  end
end

app/models/phccodesnipper/script/snippet.rb
module Phccodesnipper
  class Script::Snippet < ApplicationRecord

    # Include Core Validations
    include Phccorehelpers::Validations

    # Clean URL Initialize
    extend FriendlyId

    # Relationships
    has_many :urls, class_name: 'Phccodesnipper::Script::Url'

    # Form Fields Validation
    validates :snippet_title,
      presence: true

    validates :snippet_code,
      presence: true

    # Clean URL Define
    friendly_id :phc_nice_url_slug, use: [:slugged, :finders]

    def phc_nice_url_slug
      [
        [:snippet_title]
      ]
    end

  end
end

app/models/phccodesnipper/script/url.rb
module Phccodesnipper
  class Script::Url < ApplicationRecord

    # Include Core Validations
    phc_domain_regx = URI::regexp(%w(http https))

    # Relationships
    belongs_to :snippet, class_name: 'Phccodesnipper::Script::Snippet'

    # Form Fields Validation
    validates :script_url,
      presence: true,
      format: {  :with => phc_domain_regx, message: "Please follow this URL format http or https://www.**********.com" }

  end
end

app/controllers/phccodesnipper/application_controller.rb
module Phccodesnipper
  class ApplicationController < ActionController::Base

    # Security Filters
    protect_from_forgery with: :exception

    # Load Requried Helper Files
    helper Phccorehelpers::Engine.helpers
    helper Phcmenus::Engine.helpers
    helper Phctitleseo::Engine.helpers
    helper Phcnotifi::Engine.helpers
    helper Phcaccounts::Engine.helpers

    # Papertrail Whodunnit Username
    def user_for_paper_trail
      current_user ? current_user.username : 'Public user'
    end

    private

  end
end

app/controllers/phccodesnipper/script/snippets_controller.rb
require_dependency "phccodesnipper/application_controller"

module Phccodesnipper
  class Script::SnippetsController < ApplicationController

    # Include Core Helpers, Security & Action Filters
    include Phccorehelpers::PhcpluginsHelper
    before_action :authenticate_user!
    before_action :set_script_snippet, only: [:show, :edit, :update, :destroy]

    # INDEX
    def index
      @script_snippets = Script::Snippet.all
    end

    # SHOW
    def show
    end

    # NEW
    def new
      @script_snippet = Script::Snippet.new
    end

    # EDIT
    def edit
    end

    # CREATE
    def create
      @script_snippet = Script::Snippet.new(script_snippet_params)
      if @script_snippet.save
        redirect_to @script_snippet, :flash => { :success => 'Snippet was successfully created.' }
      else
        render :new
      end
    end

    # UPDATE
    def update
      if @script_snippet.update(script_snippet_params)
        redirect_to @script_snippet, :flash => { :success => 'Snippet was successfully updated.' }
      else
        render :edit
      end
    end

    # DELETE
    def destroy
      @script_snippet.destroy
      redirect_to script_snippets_url, :flash => { :error => 'Snippet was successfully destroyed.' }
    end

    private

    # Common Callbacks
    def set_script_snippet
      @script_snippet = Script::Snippet.find(params[:id])
    end

    # Whitelist
    def script_snippet_params
      params.require(:script_snippet).permit(:snippet_title, :snippet_code)
    end

  end
end

app/controllers/phccodesnipper/script/urls_controller.rb
require_dependency "phccodesnipper/application_controller"

module Phccodesnipper
  class Script::UrlsController < ApplicationController

    # Include Core Helpers, Security & Action Filters
    include Phccorehelpers::PhcpluginsHelper
    before_action :authenticate_user!
    before_action :set_script_url, only: [:show, :edit, :update, :destroy]

    # INDEX
    def index
      snippet = Script::Snippet.find(params[:snippet_id])
      @script_urls = snippet.urls.all
    end

    # SHOW
    def show
      script_snippet = Script::Snippet.find(params[:snippet_id])
      @script_url = script_snippet.urls.find(params[:id])
    end

    # NEW
    def new
      script_snippet = Script::Snippet.find(params[:snippet_id])
      @script_url = script_snippet.urls.build
    end

    # EDIT
    def edit
    end

    # CREATE
    def create
      @script_snippet = Script::Snippet.find(params[:snippet_id])
      @script_url = @script_snippet.urls.create(script_url_params)
      @script_url.user_id = current_user.id
      if @script_url.save
        redirect_to script_snippet_urls_path, :flash => { :success => 'Script url was successfully created.' }
      else
        render :new
      end
    end

    # UPDATE
    def update
      @script_snippet = Script::Snippet.find(params[:snippet_id])
      if @script_url.update(script_url_params)
        redirect_to script_snippet_urls_path, :flash => { :success => 'Script url was successfully updated.' }
      else
        render :edit
      end
    end

    # DELETE
    def destroy
      @script_snippet = Script::Snippet.find(params[:snippet_id])
      @script_url = @script_snippet.urls.find(params[:id])
      @script_url.destroy
      redirect_to script_snippet_urls_path, :flash => { :error => 'Script url was successfully destroyed.' }
    end

    private

    # Common Callbacks
    def set_script_url
      @script_url = Script::Url.find(params[:id])
    end

    # Whitelist
    def script_url_params
      params.require(:script_url).permit(:script_url, :snippet_id)
    end

  end
end

app/helpers/phccodesnipper/application_helper.rb
module Phccodesnipper
  module ApplicationHelper
  end
end

app/helpers/phccodesnipper/script/posts_helper.rb
module Phccodesnipper
  module Script::PostsHelper
  end
end

app/helpers/phccodesnipper/script/snippets_helper.rb
module Phccodesnipper
  module Script::SnippetsHelper
  end
end

app/helpers/phccodesnipper/script/urls_helper.rb
module Phccodesnipper
  module Script::UrlsHelper
  end
end

app/views/layouts/phccodesnipper/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <!-- SEO System -->
  <% phc_seo_title "PHCCodeSnipper by PHCDevworks" %>
  <% phc_seo_description "Application to manage and post code snippets." %>
  <!-- SEO System -->

  <!-- SEO and Site Description -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title><%= yield(:phc_seo_title) %></title>
  <meta name="description" content="<%= yield(:phc_seo_description) %>">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
  <link rel="canonical" href="http://phcdevworks.com">
  <!-- SEO and Site Description -->

  <!-- Rails Security Tags -->
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- Rails Security Tags -->

  <!-- CSS Styles -->
  <%= stylesheet_link_tag 'phccodesnipper/application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- CSS Styles -->

  <!-- Font -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700"/>
  <!-- Font -->

</head>
<body>

  <!-- Page Container -->
  <div id="page-container" class="fade page-sidebar-fixed page-header-fixed">

    <!-- Page Header -->
    <div id="header" class="header navbar-default">
      <%= render 'layouts/phccodesnipper/components/backend/navigation/top_menu' %>
    </div>
    <!-- Page Header -->

    <!-- Page Sidebar -->
    <div id="sidebar" class="sidebar">
      <%= render 'layouts/phccodesnipper/components/backend/sidebars/side_menu' %>
    </div>
    <div class="sidebar-bg"></div>
    <!-- Page Sidebar -->

    <!-- Page Content -->
    <div id="content" class="content">
      <%= render 'phcnotifi/default/notifications' %>
      <%= yield %>
    </div>
    <!-- Page Content -->

    <!-- Footer Content -->
    <div id="footer" class="footer mb-4">
      <%= render 'layouts/phccodesnipper/components/backend/footer/footer' %>
    </div>
    <!-- Footer Content -->

  </div>
  <!-- Page Container -->

  <!-- JavaScript -->
  <%= javascript_include_tag "phccodesnipper/application", 'data-turbolinks-track': 'reload' %>
  <!-- JavaScript -->

  <!-- JavaScript Loader -->
  <script>
    $(document).ready(function() {
      App.init();
    });
  </script>
  <!-- JavaScript Loader -->

</body>
</html>

app/views/layouts/phccodesnipper/components/backend/footer/_footer.html.erb
<!-- Footer -->
<span class="float-left">
  2012-<%= Time.now.year %> -
  <strong>PHC</strong>CodeSnipper -
  Engine v<%= Gem.loaded_specs["phccodesnipper"].version.to_s %>
</span>
<span class="float-right">
  Developed with <i class="fas fa-heart hanna_hearts"></i> by
  <a class="phcnet_copyright" href="https://phcdevworks.com/"><strong>PHC</strong>Devworks</a>
</span>
<!-- Footer -->

app/views/layouts/phccodesnipper/components/backend/navigation/_top_menu.html.erb
<!-- Topbar - Navigation Header -->
<div class="navbar-header">
  <%= link_to phccodesnipper.script_snippets_path, class: "navbar-brand" do %>
    <strong>PHC</strong>CodeSnipper
  <% end %>
  <button type="button" class="navbar-toggle" data-click="sidebar-toggled">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
</div>
<!-- Topbar - Navigation Header -->

<!-- Topbar - Navigation Main -->
<% if current_user %>
  <ul class="navbar-nav navbar-right">

    <!-- Topbar - Navigation Main - User Menu -->
    <li class="dropdown navbar-user">
      <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
        <%= image_tag current_user.gravatar_url %>
        <span class="d-none d-md-inline"><%= current_user.firstname + ' ' + current_user.lastname  %></span> <b class="caret"></b>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <%= link_to phcaccounts.edit_user_registration_path, class: "dropdown-item" do %>
          <i class="fas fa-cogs"></i> Account Settings
        <% end %>
        <%= link_to phcaccounts.destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
          <i class="fas fa-sign-out-alt"></i> Logout
        <% end %>
      </div>
    </li>
    <!-- Topbar - Navigation Main - User Menu -->

  </ul>
<% end %>
<!-- Topbar - Navigation Main -->

app/views/layouts/phccodesnipper/components/backend/sidebars/_side_menu.html.erb
<!-- Sidebar for PHCDevworks Engines -->
<div data-scrollbar="true" data-height="100%">

  <!-- Sidebar - User Profile Menu -->
  <ul class="nav">
    <% if current_user %>
      <li class="nav-profile">
        <a href="javascript:;" data-toggle="nav-profile">
          <div class="cover with-shadow"></div>
          <div class="image">
            <%= image_tag current_user.gravatar_url %>
          </div>
          <div class="info">
            <b class="caret pull-right"></b>
            <%= current_user.firstname + ' ' + current_user.lastname  %>
            <small><%= current_user.username %></small>
          </div>
        </a>
      </li>
      <li>
        <ul class="nav nav-profile">
          <li>
            <%= link_to phcaccounts.edit_user_registration_path do %>
              <i class="fas fa-cogs"></i> Account Settings
            <% end %>
          </li>
          <li>
            <%= link_to phcaccounts.destroy_user_session_path do %>
              <i class="fas fa-sign-out-alt"></i> Logout
            <% end %>
          </li>
        </ul>
      </li>
    <% end %>
  </ul>
  <!-- Sidebar - User Profile Menu -->

  <!-- Sidebar - Sidebar Navigation -->
  <ul class="nav">

    <% if defined?phccodesnipper %>
      <!-- Sidebar - Sidebar Navigation - PHCCodeSnipper -->
      <li class="nav-header">Code Snippets</li>
      <li class="has-sub">
        <a href="javascript:;">
          <b class="caret"></b>
          <i class="fas fa-newspaper"></i>
          <span>Code Snippets</span>
        </a>
        <ul class="sub-menu">
          <li class="<%= phc_menus_active_controller('phccodesnipper/script/posts') %>"><%= link_to 'Snippet Index', phccodesnipper.script_snippets_path %></li>
          <li class="<%= phc_menus_active_controller('phccodesnipper/script/posts#new') %>"><%= link_to 'New Snippet', phccodesnipper.new_script_snippet_path %></li>
        </ul>
      </li>
      <!-- Sidebar - Sidebar Navigation - PHCCodeSnipper -->
    <% end %>

    <% if defined?phcpress %>
      <!-- Sidebar - Sidebar Navigation - PHCPress -->
      <li class="nav-header">Article Management</li>
      <li class="has-sub">
        <a href="javascript:;">
          <b class="caret"></b>
          <i class="fas fa-newspaper"></i>
          <span>Article Posts</span>
        </a>
        <ul class="sub-menu">
          <li class="<%= phc_menus_active_controller('phcpress/article/posts') %>"><%= link_to('Article Index', phcpress.article_posts_path) %></li>
          <li class="<%= phc_menus_active_controller('phcpress/article/posts#new') %>"><%= link_to('New Aritcle', phcpress.new_article_post_path) %></li>
        </ul>
      </li>
      <li class="has-sub">
        <a href="javascript:;">
          <b class="caret"></b>
          <i class="fas fa-sitemap"></i>
          <span>Article Categories</span>
        </a>
        <ul class="sub-menu">
          <li class="<%= phc_menus_active_controller('phcpress/article/categories') %>"><%= link_to('Category Index', phcpress.article_categories_path) %></li>
          <li class="<%= phc_menus_active_controller('phcpress/article/categories#new') %>"><%= link_to('New Category', phcpress.new_article_category_path) %></li>
        </ul>
      </li>
      <!-- Sidebar - Sidebar Navigation - PHCPress -->
    <% end %>

    <% if defined?phcmembers %>
      <!-- Sidebar - Sidebar Navigation - PHCMembers -->
      <li class="nav-header">Membership Manager</li>
      <li class="has-sub">
        <a href="javascript:;">
          <b class="caret"></b>
          <i class="fas fa-users"></i>
          <span>Member's Data</span>
        </a>
        <ul class="sub-menu">
          <li class="<%= phc_menus_active_controller('phcmembers/member/profiles') %>"><%= link_to('Profile Index', phcmembers.member_profiles_path) %></li>
          <li class="<%= phc_menus_active_controller('phcmembers/member/profiles#new') %>"><%= link_to('New Member Profile', phcmembers.new_member_profile_path) %></li>
        </ul>
      </li>
      <li class="has-sub">
        <a href="javascript:;">
          <b class="caret"></b>
          <i class="fas fa-list-alt"></i>
          <span>Member's Directory</span>
        </a>
        <ul class="sub-menu">
          <li class="<%= phc_menus_active_controller('phcmembers/directory/categories') %>"><%= link_to('Directory Index', phcmembers.directory_categories_path) %></li>
          <li class="<%= phc_menus_active_controller('phcmembers/directory/categories#new') %>"><%= link_to('New Directory Listing', phcmembers.new_directory_category_path) %></li>
        </ul>
      </li>
      <!-- Sidebar - Sidebar Navigation - PHCMembers -->
    <% end %>

    <% if defined?phcscriptcdn %>
      <!-- Sidebar - Sidebar Navigation - PHCScriptCDN -->
      <li class="nav-header">Script Management</li>
      <li class="has-sub">
        <a href="javascript:;">
          <b class="caret"></b>
          <i class="fas fa-newspaper"></i>
          <span>Script Posts</span>
        </a>
        <ul class="sub-menu">
          <li class="<%= phc_menus_active_controller('phcscriptcdn/script/listings') %>"><%= link_to "All Script Listings", phcscriptcdn.script_listings_path %></li>
          <li class="<%= phc_menus_active_controller('phcscriptcdn/script/listings#new') %>"><%= link_to "Add a New Listing", phcscriptcdn.new_script_listing_path %></li>
        </ul>
      </li>
      <li class="has-sub">
        <a href="javascript:;">
          <b class="caret"></b>
          <i class="fas fa-sitemap"></i>
          <span>Script Extras</span>
        </a>
        <ul class="sub-menu">
          <li class="<%= phc_menus_active_controller('phcscriptcdn/script/authors') %>"><%= link_to "Script Authors", phcscriptcdn.script_authors_path %></li>
          <li class="<%= phc_menus_active_controller('phcscriptcdn/script/licences') %>"><%= link_to "Script Licences", phcscriptcdn.script_licences_path %></li>
          <li class="<%= phc_menus_active_controller('phcscriptcdn/script/extensions') %>"><%= link_to "Script Extensions", phcscriptcdn.script_extensions_path %></li>
          <li class="<%= phc_menus_active_controller('phcscriptcdn/script/versions') %>"><%= link_to "Script Versions", phcscriptcdn.script_versions_path %></li>
        </ul>
      </li>
      <!-- Sidebar - Sidebar Navigation - PHCScriptCDN -->
    <% end %>

    <% if current_user && current_user.admin? %>
      <!-- Sidebar - Sidebar Navigation - PHCAccounts Admin Options -->
      <li class="nav-header">User Administration</li>
      <li class="has-sub">
        <a href="javascript:;">
          <b class="caret"></b>
          <i class="fas fa-user"></i>
          <span>Admin</span>
        </a>
        <ul class="sub-menu">
          <li class="<%= phc_menus_active_controller('phcaccounts/admin/users') %>"><%= link_to 'User List', phcaccounts.admin_users_path %></li>
        </ul>
      </li>
      <!-- Sidebar - Sidebar Navigation - PHCAccounts Admin Options -->
    <% end %>

    <% if current_user %>
      <!-- Sidebar - Sidebar Navigation - PHCAccounts User Options -->
      <li class="nav-header">Your Account</li>
      <li class="has-sub">
        <a href="javascript:;">
          <b class="caret"></b>
          <i class="fas fa-user"></i>
          <span>Accounts Settings</span>
        </a>
        <ul class="sub-menu">
          <li class="<%= phc_menus_active_controller('phcaccounts/user/edit') %>"><%= link_to 'Settings', phcaccounts.edit_user_registration_path %></li>
          <li class="<%= phc_menus_active_controller('phcaccounts/user/new') %>"><%= link_to 'Logout', phcaccounts.destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
      <!-- Sidebar - Sidebar Navigation - PHCAccounts User Options -->
    <% end %>

    <!-- Sidebar - Sidebar Minifier -->
    <li>
      <a href="javascript:;" class="sidebar-minify-btn" data-click="sidebar-minify">
        <i class="fa fa-angle-double-left"></i>
      </a>
    </li>
    <!-- Sidebar - Sidebar Minifier -->

  </ul>
  <!-- Sidebar - Sidebar Navigation -->

</div>
<!-- Sidebar for PHCDevworks Engines -->

app/views/phccodesnipper/script/snippets/index.html.erb
<!-- Title System -->
<% phc_title "Code Snippet Manager" %>
<% phc_title_tagline "Code Snippet Index" %>
<% phc_breadcrumb_one yield(:phc_title_tagline) %>
<% phc_breadcrumb_two link_to "Code Snippet Index", phccodesnipper.script_snippets_path %>
<!-- Title System -->

<!-- Page Bradcrumbs -->
<ol class="breadcrumb pull-right">
  <li class="breadcrumb-item"><%= yield(:phc_breadcrumb_one) %></li>
  <li class="breadcrumb-item active"><%= yield(:phc_breadcrumb_two) %></li>
</ol>
<!-- Page Bradcrumbs -->

<!-- Page Header -->
<h1 class="page-header"><%= yield(:phc_title) %></h1>
<!-- Page Header -->

<!-- Page & Panel Content -->
<div class="panel panel-inverse">
  <!-- Panel Heading -->
  <div class="panel-heading">
    <div class="panel-heading-btn">
      <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
      <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
      <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
    </div>
    <h4 class="panel-title"><%= yield(:phc_title_tagline) %></h4>
  </div>
  <!-- Panel Heading -->
  <!-- Panel Body -->
  <div class="panel-body">
    <!-- Table - Snippet Index -->
    <div class="table-responsive">
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Snippet Title</th>
            <th>Snippet Summary</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @script_snippets.each do |script_snippet| %>
            <tr>
              <td><%= script_snippet.snippet_title %></td>
              <td><%= truncate(script_snippet.snippet_code, :length => 80) %></td>
              <td>
                <div class="btn-group d-flex" role="group">
                  <%= link_to 'Details', script_snippet, class: "btn btn-purple btn-xs" %>
                  <%= link_to 'Update', edit_script_snippet_path(script_snippet), class: "btn btn-primary btn-xs" %>
                  <%= link_to 'Remmove', script_snippet, method: :delete, data: { confirm: 'Are you sure? This will aslo delte the snippet urls.' }, class: "btn btn-danger btn-xs" %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to phccodesnipper.new_script_snippet_path, class: "btn btn-primary btn-sm" do %>
        <i class="fas fa-plus-circle"></i>
        Add a New Code Snippet
      <% end %>
    </div>
    <!-- Table - Snippet Index -->
  </div>
  <!-- Panel Body -->
</div>
<!-- Page & Panel Content -->

app/views/phccodesnipper/script/urls/edit.html.erb
<!-- Title System -->
<% phc_title "Code Snippet Manager" %>
<% phc_title_tagline "Update Asset URL" %>
<% phc_breadcrumb_one link_to "Code Snippet Index", phccodesnipper.script_snippets_path %>
<% phc_breadcrumb_two yield(:phc_title_tagline) %>
<!-- Title System -->

<!-- Page Bradcrumbs -->
<ol class="breadcrumb pull-right">
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_one) %></li>
	<li class="breadcrumb-item active"><%= yield(:phc_breadcrumb_two) %></li>
</ol>
<!-- Page Bradcrumbs -->

<!-- Page Header -->
<h1 class="page-header"><%= yield(:phc_title) %></h1>
<!-- Page Header -->

<!-- Page & Panel Content -->
<div class="panel panel-inverse">
	<!-- Panel Heading -->
	<div class="panel-heading">
		<div class="panel-heading-btn">
			<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
			<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
			<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
		</div>
		<h4 class="panel-title"><%= yield(:phc_title_tagline) %></h4>
	</div>
	<!-- Panel Heading -->
	<!-- Panel Body -->
	<div class="panel-body">
		<!-- Form to Edit Script Snippet Asset URLS  -->
		<%= render 'form', { form_url: script_snippet_url_path } %>
		<!-- Form to Edit Script Snippet Asset URLS  -->
	</div>
	<!-- Panel Body -->
</div>
<!-- Page & Panel Content -->

app/views/phccodesnipper/script/urls/index.html.erb
<!-- Title System -->
<% phc_title "Code Snippet Manager" %>
<% phc_title_tagline "Update Asset Index" %>
<% phc_breadcrumb_one yield(:phc_title_tagline) %>
<% phc_breadcrumb_two link_to "Code Snippet Index", phccodesnipper.script_snippets_path %>
<!-- Title System -->

<!-- Page Bradcrumbs -->
<ol class="breadcrumb pull-right">
  <li class="breadcrumb-item"><%= yield(:phc_breadcrumb_one) %></li>
  <li class="breadcrumb-item active"><%= yield(:phc_breadcrumb_two) %></li>
</ol>
<!-- Page Bradcrumbs -->

<!-- Page Header -->
<h1 class="page-header"><%= yield(:phc_title) %></h1>
<!-- Page Header -->

<!-- Page & Panel Content -->
<div class="panel panel-inverse">
  <!-- Panel Heading -->
  <div class="panel-heading">
    <div class="panel-heading-btn">
      <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
      <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
      <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
    </div>
    <h4 class="panel-title"><%= yield(:phc_title_tagline) %></h4>
  </div>
  <!-- Panel Heading -->
  <!-- Panel Body -->
  <div class="panel-body">
    <!-- Table - Snippet Index -->
    <div class="table-responsive">
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Script Url</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @script_urls.each do |script_url| %>
            <tr>
              <td><%= script_url.script_url %></td>
              <td>
                <div class="btn-group d-flex" role="group">
                  <%= link_to 'Details', script_snippet_url_path(script_url.snippet, script_url), class: "btn btn-purple btn-xs" %>
                  <%= link_to 'Update', edit_script_snippet_url_path(script_url.snippet, script_url), class: "btn btn-primary btn-xs" %>
                  <%= link_to 'Remove', script_snippet_url_path(script_url.snippet, script_url), method: :delete, data: { confirm: 'Are you sure? This action cannot be reversed.' }, class: "btn btn-danger btn-xs" %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to phccodesnipper.new_script_snippet_url_path, class: "btn btn-primary btn-sm" do %>
        <i class="fas fa-plus-circle"></i>
        Add a New Script URL
      <% end %>
    </div>
    <!-- Table - Snippet Index -->
  </div>
  <!-- Panel Body -->
</div>
<!-- Page & Panel Content -->